// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU4AhGwZMsGmLK97iQZAvfxQ2xBJD9SYQ',
    appId: '1:92855436550:web:b8210147f001d12faf4a87',
    messagingSenderId: '92855436550',
    projectId: 'uesb-formulario',
    authDomain: 'uesb-formulario.firebaseapp.com',
    databaseURL: 'https://uesb-formulario-default-rtdb.firebaseio.com',
    storageBucket: 'uesb-formulario.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL5e8iteOPaMcCgTJx-2QLVUOV-pED63o',
    appId: '1:92855436550:android:f42b7d6c0288f3feaf4a87',
    messagingSenderId: '92855436550',
    projectId: 'uesb-formulario',
    databaseURL: 'https://uesb-formulario-default-rtdb.firebaseio.com',
    storageBucket: 'uesb-formulario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPwWtVTfziIQo1_jjcThuuzhb7QsT_zVA',
    appId: '1:92855436550:ios:d9ce0a2bcc88ec89af4a87',
    messagingSenderId: '92855436550',
    projectId: 'uesb-formulario',
    databaseURL: 'https://uesb-formulario-default-rtdb.firebaseio.com',
    storageBucket: 'uesb-formulario.appspot.com',
    androidClientId: '92855436550-kp0q3014mf6vnqe087rtfno3q1e42s6f.apps.googleusercontent.com',
    iosClientId: '92855436550-cfq5645mdo8nag0rr1vf2cjo7cmraeo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.uesbForms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPwWtVTfziIQo1_jjcThuuzhb7QsT_zVA',
    appId: '1:92855436550:ios:d9ce0a2bcc88ec89af4a87',
    messagingSenderId: '92855436550',
    projectId: 'uesb-formulario',
    databaseURL: 'https://uesb-formulario-default-rtdb.firebaseio.com',
    storageBucket: 'uesb-formulario.appspot.com',
    androidClientId: '92855436550-kp0q3014mf6vnqe087rtfno3q1e42s6f.apps.googleusercontent.com',
    iosClientId: '92855436550-cfq5645mdo8nag0rr1vf2cjo7cmraeo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.uesbForms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU4AhGwZMsGmLK97iQZAvfxQ2xBJD9SYQ',
    appId: '1:92855436550:web:1d64a69791aab108af4a87',
    messagingSenderId: '92855436550',
    projectId: 'uesb-formulario',
    authDomain: 'uesb-formulario.firebaseapp.com',
    databaseURL: 'https://uesb-formulario-default-rtdb.firebaseio.com',
    storageBucket: 'uesb-formulario.appspot.com',
  );
}
